apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsbp-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: devopsbp
  template:
    metadata:
      labels:
        app: devopsbp
    spec:
      containers:
      - name: devopsbp
        image: gcr.io/tonal-depth-427415-s0/devopsbp:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: devopsbp-config
        - secretRef:
            name: devopsbp-secret
