name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.15.0'
    - name: Install dependencies
      run: npm install
    - name: Install sqlite3 globally
      run: npm install -g sqlite3 --save
    - name: Rebuild npm packages
      run: npm rebuild
    - name: Verify sqlite3 installation
      run: npm list -g sqlite3
    - name: Ensure correct permissions for project directory
      run: chmod -R 755 .
    - name: Start application
      run: |
        npm start &
        sleep 5
    - name: Stop application
      run: kill $(lsof -t -i:8000)
    - name: Run tests
      run: npm test
    - name: Static Code Analysis
      run: |
        npm install -g eslint
        npx eslint .
    - name: Code Coverage
      run: |
        npm install -g nyc
        nyc npm test
    - name: Build Docker image
      run: docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/devopsbp:latest
    - name: Push Docker image
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo $GCP_SERVICE_ACCOUNT_KEY | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/devopsbp:latest
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
          version: 'latest'
    - name: Authenticate with GKE
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials my-cluster --zone us-east1-b --project ${{ secrets.GCP_PROJECT_ID }}
    - name: Deploy ConfigMap to Kubernetes
      run: kubectl apply -f configmap.yaml
    - name: Deploy Secret to Kubernetes
      run: kubectl apply -f secret.yaml
    - name: Deploy Deployment to Kubernetes
      run: kubectl apply -f deployment.yaml
    - name: Deploy Service to Kubernetes
      run: kubectl apply -f service.yaml
    - name: Deploy Ingress to Kubernetes
      run: kubectl apply -f ingress.yaml
