name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.15.0'
    - name: Install dependencies
      run: npm install
    - name: Install sqlite3 globally
      run: npm install -g sqlite3 --save
    - name: Rebuild npm packages
      run: npm rebuild
    - name: Verify sqlite3 installation
      run: npm list -g sqlite3
    - name: Ensure correct permissions for project directory
      run: chmod -R 755 .
    - name: Start application
      run: |
        npm start &
        sleep 5
    - name: Stop application
      run: kill $(lsof -t -i:8000)
    - name: Run tests
      run: npm test
    - name: Static Code Analysis
      run: |
        npm install -g eslint
        npx eslint .
    - name: Code Coverage
      run: |
        npm install -g nyc
        nyc npm test
    - name: Build Docker image
      run: docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/devopsbp:latest

    - name: Push Docker image
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo $GCP_SERVICE_ACCOUNT_KEY | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/devopsbp:latest
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
    
    - name: Authenticate to Google
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      
    - uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin"
  
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: my-cluster
        location: us-east1-b

    - name: Deploy ConfigMap to Kubernetes
      run: kubectl apply -f configmap.yaml
    - name: Deploy Secret to Kubernetes
      run: kubectl apply -f secret.yaml
    - name: Deploy Deployment to Kubernetes
      run: kubectl apply -f deployment.yaml
    - name: Deploy Service to Kubernetes
      run: kubectl apply -f service.yaml
    - name: Deploy Ingress to Kubernetes
      run: kubectl apply -f ingress.yaml
